baseURL = "http://estherolatunde.com/"
languageCode = "en-us"
title = "Esther Olatunde"

theme = "kiss"
copyright = "&copy; <a href=\"https://github.com/esteedqueen\">Esther Olatunde</a> 2018"
googleAnalytics = ""
# Number of posts per page
Paginate = 5
enableRobotsTXT = true 

[[menu.main]]
    name = "About"
    pre = "<i class='fa fa-heart'></i>"
    identifier = "about"
    url = "/about/"


[params.assets]
customCSS = ["css/custom.css"]

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = false # Adds OpenGraph and Twitter cards
homeTitle = "Esther Olatunde's Personal Website"
poweredby = false # Adds powered by Hugo and Kiss below Copyright section

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter Page username. If not set, params.social.twitter will be used.

[params.social]

github = "esteedqueen"
twitter = "MsEOlatunde"

[taxonomies]
tag ="tags"

[blackfriday]
hrefTargetBlank = true

