baseURL = "https://estherolatunde.com"
languageCode = "en-us"
title = "Esther Olatunde"

theme = "kiss"
copyright = "&copy; <a href=\"https://github.com/esteedqueen\">Esther Olatunde</a> 2018"
googleAnalytics = "UA-113891354-1"
# Number of posts per page
Paginate = 5
enableRobotsTXT = true

[author]
name = "Esther Olatunde"
email = "ea.olatunde@gmail.com"

[[menu.main]]
    name = "About"
    pre = "<i class='fa fa-heart'></i>"
    identifier = "about"
    url = "/about/"


[params.assets]
customCSS = ["css/custom.css"]

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = true # Adds OpenGraph and Twitter cards
homeTitle = "Esther Olatunde's Personal Website"
poweredby = false # Adds powered by Hugo and Kiss below Copyright section

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "MsEOlatunde" # Twitter Page username. If not set, params.social.twitter will be used.

[params.social]

github = "esteedqueen"
twitter = "MsEOlatunde"
email = "ea.olatunde@gmail.com"

[taxonomies]
category= "categories"
tag= "tags"


